#!/bin/bash

SVNDIR="/usr/src/astguiclient"

if [ ! -d "$SVNDIR" ]; then
    echo "Making $SVNDIR"
    mkdir -p "$SVNDIR"
fi

cd $SVNDIR
echo "Checking out ViciDial SVN..."
svn checkout svn://svn.eflo.net:3690/agc_2-X/trunk
